/*
 * Czech (Čeština) translation. Mirrors the shape of `en` exactly — the
 * `Strings` type enforces it, so a missing or mistyped key fails the build.
 * Functions interpolate values; Czech needs three plural forms (1, 2–4, 5+),
 * handled with the `plural` helper below.
 */

import type { Strings } from './en'

/** Pick the right Czech plural form: `one` (1), `few` (2–4), `many` (0, 5+). */
function plural(n: number, one: string, few: string, many: string): string {
  if (n === 1) return one
  if (n >= 2 && n <= 4) return few
  return many
}

export const cs: Strings = {
  appName: 'pedift',
  tagline: 'Úpravy PDF v soukromí vašeho prohlížeče',

  privacy: {
    badge: 'Soukromé a offline',
    line: 'Vaše soubory nikdy neopustí toto zařízení. Nic se nenahrává — veškeré úpravy probíhají ve vašem prohlížeči.',
  },

  theme: {
    toLight: 'Přepnout na světlý režim',
    toDark: 'Přepnout na tmavý režim',
  },

  language: {
    label: 'Jazyk',
    english: 'English',
    czech: 'Čeština',
    switchTo: 'Změnit jazyk',
  },

  landing: {
    dropTitle: 'Přetáhněte sem PDF nebo klikněte pro otevření',
    dropHint: 'nebo vyberte soubor z počítače',
    dropActive: 'Uvolněte pro otevření',
    openButton: 'Otevřít PDF',
    quickToolsTitle: 'Rychlé nástroje',
    quickToolsHint: 'Jednorázové úkony — bez nutnosti otevírat editor',
    or: 'nebo',
    saveThisPage: 'Uložit tuto stránku pro offline použití',
  },

  quickTools: {
    merge: { title: 'Sloučit PDF', desc: 'Spojí několik PDF do jednoho' },
    imagesToPdf: { title: 'Obrázky → PDF', desc: 'Převede obrázky JPG/PNG na PDF' },
    compress: { title: 'Komprimovat', desc: 'Zmenší PDF překódováním obrázků' },
    protect: { title: 'Zabezpečit / Odebrat heslo', desc: 'Přidá nebo odebere heslo' },
  },

  common: {
    cancel: 'Zrušit',
    close: 'Zavřít',
    back: 'Zpět',
    next: 'Další',
    done: 'Hotovo',
    apply: 'Použít',
    save: 'Uložit',
    download: 'Stáhnout',
    add: 'Přidat',
    remove: 'Odebrat',
    delete: 'Smazat',
    duplicate: 'Duplikovat',
    rotate: 'Otočit',
    confirm: 'Potvrdit',
    yes: 'Ano',
    no: 'Ne',
    optional: 'volitelné',
    of: 'z',
    page: 'Stránka',
    pages: 'Stránky',
    all: 'Vše',
    none: 'Žádné',
    loading: 'Pracuji…',
    dragToReorder: 'Přetažením změníte pořadí',
    addFiles: 'Přidat soubory',
    addMore: 'Přidat další',
    chooseFiles: 'Vybrat soubory',
    moveUp: 'Posunout nahoru',
    moveDown: 'Posunout dolů',
    dismiss: 'Zavřít',
    fromPage: 'Od stránky',
    toPage: 'Do stránky',
    applied: 'Změny použity',
    invalidRange: 'Zadejte platný rozsah stránek.',
  },

  workspace: {
    documentMenu: 'Dokument',
    save: 'Uložit PDF',
    saving: 'Ukládání…',
    saved: 'Staženo',
    undo: 'Zpět',
    redo: 'Znovu',
    zoomIn: 'Přiblížit',
    zoomOut: 'Oddálit',
    fitPage: 'Přizpůsobit stránku',
    fitWidth: 'Přizpůsobit šířku',
    closeDocument: 'Zavřít dokument',
    closeConfirm: 'Zavřít tento dokument? Všechny neuložené úpravy budou zahozeny.',
    discardAndClose: 'Zahodit změny',
    resetZoom: 'Obnovit na 100 %',
    pagesPanel: 'Stránky',
    pageOf: (n: number, total: number) => `Stránka ${n} z ${total}`,
    selectedCount: (n: number) => `Vybráno: ${n}`,
  },

  find: {
    open: 'Najít (Ctrl+F)',
    placeholder: 'Najít v dokumentu',
    previous: 'Předchozí výskyt',
    next: 'Další výskyt',
    close: 'Zavřít hledání',
    noResults: 'Nic nenalezeno',
    counter: (current: number, total: number) => `${current} z ${total}`,
  },

  tools: {
    select: 'Vybrat',
    text: 'Textové pole',
    replaceText: 'Nahradit text',
    highlight: 'Zvýraznit',
    pen: 'Pero',
    shapes: 'Tvary',
    rectangle: 'Obdélník',
    ellipse: 'Elipsa',
    line: 'Čára',
    arrow: 'Šipka',
    whiteout: 'Bělítko',
    whiteoutNote: 'Obsah pouze vizuálně zakryje — skrytý text zůstává v souboru. K odstranění použijte Redakci.',
    redaction: 'Redakce',
    redactBlack: 'Černý pruh',
    redactWhite: 'Bílý pruh',
    redactNote: 'Trvale odstraní zakrytý text a obrázky — stránka se uloží jako sloučený obrázek.',
    image: 'Vložit obrázek',
    signature: 'Podpis',
    stamp: 'Razítko',
    pageNumbers: 'Čísla stránek',
    watermark: 'Vodoznak',
    color: 'Barva',
    colorAriaLabel: 'Barva',
    fill: 'Výplň',
    strokeWidth: 'Tloušťka čáry',
    fontSize: 'Velikost písma',
    font: 'Písmo',
    fontHelvetica: 'Helvetica',
    fontTimes: 'Times',
    fontCourier: 'Courier',
    opacity: 'Průhlednost',
    annotationToolbarAriaLabel: 'Nástroje pro anotace',
    align: 'Zarovnání',
    alignLeft: 'Zarovnat vlevo',
    alignCenter: 'Zarovnat na střed',
    alignRight: 'Zarovnat vpravo',
  },

  pagesPanel: {
    reorder: 'Změnit pořadí (přetažením)',
    rotateLeft: 'Otočit doleva',
    rotateRight: 'Otočit doprava',
    delete: 'Smazat stránku/stránky',
    duplicate: 'Duplikovat stránku/stránky',
    extract: 'Extrahovat do nového PDF',
    split: 'Rozdělit…',
    insert: 'Vložit stránky…',
    crop: 'Oříznout…',
    exportImage: 'Exportovat jako obrázek…',
    deleteConfirm: (n: number) =>
      plural(
        n,
        'Smazat tuto stránku?',
        `Smazat tyto ${n} stránky?`,
        `Smazat těchto ${n} stránek?`,
      ),
    selectAll: 'Vybrat vše',
    deselectAll: 'Zrušit výběr',
    movedTo: (n: number, total: number) => `Přesunuto na pozici ${n} z ${total}`,
  },

  documentMenu: {
    fillForms: 'Vyplnit formuláře',
    flatten: 'Sloučit vrstvy',
    ocr: 'OCR (rozpoznat text)…',
    metadata: 'Metadata…',
    protect: 'Zabezpečit / Odebrat heslo…',
    compress: 'Komprimovat…',
    properties: 'Vlastnosti',
  },

  dialogs: {
    merge: {
      title: 'Sloučit PDF',
      hint: 'Přidejte dvě nebo více PDF, přetažením nastavte pořadí a sloučte.',
      empty: 'Pro sloučení přidejte alespoň dvě PDF.',
      mergeButton: 'Sloučit a stáhnout',
      merging: 'Slučuji…',
    },
    imagesToPdf: {
      title: 'Obrázky → PDF',
      hint: 'Přidejte obrázky JPG nebo PNG, nastavte pořadí a zvolte velikost stránky.',
      pageSize: 'Velikost stránky',
      orientation: 'Orientace',
      a4: 'A4',
      letter: 'Letter',
      fitImage: 'Přizpůsobit obrázku',
      portrait: 'Na výšku',
      landscape: 'Na šířku',
      margin: 'Okraj',
      createButton: 'Vytvořit a stáhnout',
      creating: 'Vytvářím…',
      empty: 'Přidejte alespoň jeden obrázek.',
    },
    compress: {
      title: 'Komprimovat PDF',
      hint: 'Překóduje vložené obrázky v nižší kvalitě. Výsledky se liší podle dokumentu — jde o nejlepší možný pokus a nezaručuje žádný poměr.',
      quality: 'Kvalita obrázků',
      qualityLow: 'Menší soubor',
      qualityHigh: 'Lepší kvalita',
      analyzing: 'Analyzuji obrázky…',
      before: 'Originál',
      after: 'Komprimováno',
      saved: (pct: number) => `o ${pct} % menší`,
      larger: 'Již optimalizováno — menší verzi se nepodařilo vytvořit',
      compressButton: 'Komprimovat a stáhnout',
      pickFile: 'Přetáhněte PDF ke kompresi nebo klikněte pro výběr',
      tryAgain: 'Zkusit jinou kvalitu',
    },
    protect: {
      title: 'Zabezpečit / Odebrat heslo',
      mode: 'Co chcete udělat?',
      addPassword: 'Přidat heslo',
      removePassword: 'Odebrat heslo',
      newPassword: 'Nové heslo',
      confirmPassword: 'Potvrdit heslo',
      currentPassword: 'Současné heslo',
      mismatch: 'Hesla se neshodují.',
      empty: 'Zadejte heslo.',
      protectButton: 'Použít',
      unprotectButton: 'Odebrat heslo',
      pickFile: 'Přetáhněte PDF nebo klikněte pro výběr',
      saveNote: 'Použije se na soubor při příštím uložení.',
      appliedAdd: 'Heslo nastaveno — použije se při uložení',
      appliedRemove: 'Heslo odebráno — použije se při uložení',
      unsupportedTitle: 'Ochrana heslem není dostupná',
      unsupported:
        'Tato verze neumí spolehlivě přidávat ani odebírat hesla PDF, proto je funkce vypnutá, aby nevznikaly poškozené soubory.',
    },
    split: {
      title: 'Rozdělit PDF',
      byRanges: 'Podle rozsahů stránek',
      everyN: 'Každých N stránek',
      rangesLabel: 'Rozsahy (např. 1-3, 4, 5-8)',
      everyNLabel: 'Stránek na soubor',
      note: 'Každá část se stáhne jako samostatný soubor.',
      splitButton: 'Rozdělit a stáhnout',
      invalidRanges: 'Zadejte platné rozsahy stránek v rozmezí 1–{total}.',
    },
    insert: {
      title: 'Vložit stránky',
      pickFile: 'Vyberte PDF, ze kterého chcete vložit',
      whichPages: 'Které stránky',
      allPages: 'Všechny stránky',
      somePages: 'Stránky (např. 1-3, 5)',
      somePagesPlaceholder: '1-3, 5',
      somePagesPicker: 'Vybrané stránky',
      position: 'Vložit na',
      beforePage: (n: number) => `Před stránku ${n}`,
      atEnd: 'Na konec',
      insertButton: 'Vložit',
    },
    crop: {
      title: 'Oříznout',
      hint: 'Přetažením obdélníku na stránce nastavte viditelnou oblast. Zrušíte klávesou Esc.',
      applyTo: 'Použít na',
      thisPage: 'Tuto stránku',
      allPages: 'Všechny stránky',
      reset: 'Obnovit',
      applyButton: 'Použít oříznutí',
    },
    exportImage: {
      title: 'Exportovat jako obrázek',
      format: 'Formát',
      png: 'PNG',
      jpg: 'JPG',
      scale: 'Měřítko',
      scale1x: '1× (72 dpi)',
      scale2x: '2× (144 dpi)',
      scale3x: '3× (216 dpi)',
      scale4x: '4× (288 dpi)',
      exportButton: 'Exportovat a stáhnout',
      exporting: (current: number, total: number) => `Exportuji stránku ${current} z ${total}…`,
      done: (n: number) =>
        plural(
          n,
          `Exportována ${n} stránka jako obrázek`,
          `Exportovány ${n} stránky jako obrázky`,
          `Exportováno ${n} stránek jako obrázky`,
        ),
    },
    metadata: {
      title: 'Vlastnosti dokumentu',
      titleField: 'Název',
      author: 'Autor',
      subject: 'Předmět',
      keywords: 'Klíčová slova (oddělená čárkou)',
      saveButton: 'Použít',
    },
    pageNumbers: {
      title: 'Čísla stránek',
      position: 'Pozice',
      topLeft: 'Vlevo nahoře',
      topCenter: 'Uprostřed nahoře',
      topRight: 'Vpravo nahoře',
      bottomLeft: 'Vlevo dole',
      bottomCenter: 'Uprostřed dole',
      bottomRight: 'Vpravo dole',
      format: 'Formát',
      formatPlain: '1',
      formatSlash: '1 / N',
      formatLong: 'Stránka 1 z N',
      startAt: 'Začít od',
      range: 'Stránky',
      addButton: 'Přidat čísla stránek',
      applied: 'Čísla stránek přidána',
    },
    watermark: {
      title: 'Vodoznak',
      text: 'Text vodoznaku',
      placeholder: 'např. DŮVĚRNÉ',
      addButton: 'Přidat vodoznak',
      applyTo: 'Stránky',
      applied: 'Vodoznak přidán',
    },
    signature: {
      title: 'Podpis',
      draw: 'Nakreslit',
      type: 'Napsat',
      clear: 'Vymazat',
      typePlaceholder: 'Napište své jméno',
      useButton: 'Umístit podpis',
      reuse: 'Uložené podpisy',
    },
    fillForms: {
      title: 'Vyplnit pole formuláře',
      none: 'V tomto dokumentu nebyla nalezena žádná vyplnitelná pole formuláře.',
      saveButton: 'Použít a pokračovat',
      applied: 'Pole formuláře vyplněna',
    },
    flatten: {
      title: 'Sloučit vrstvy dokumentu',
      hint: 'Zapeče pole formulářů a anotace do stránky, takže je již nelze upravovat. Po uložení nelze vrátit zpět.',
      flattenButton: 'Sloučit vrstvy',
      applied: 'Vrstvy sloučeny',
    },
    stamp: {
      title: 'Razítko',
      approved: 'SCHVÁLENO',
      draft: 'KONCEPT',
      confidential: 'DŮVĚRNÉ',
      check: 'Zaškrtnutí',
      cross: 'Křížek',
      date: 'Dnešní datum',
    },
    replaceText: {
      note: 'Nahrazení textu zakryje původní text a umožní vám ho přepsat. Písmo může vypadat jinak než originál.',
      gotIt: 'Rozumím',
    },
    ocr: {
      title: 'OCR — Rozpoznání textu',
      hint: 'Přidá neviditelnou textovou vrstvu do naskenovaných stránek, abyste mohli text vybírat a kopírovat.',
      language: 'Jazyk',
      english: 'Angličtina',
      czech: 'Čeština',
      scope: 'Stránky',
      scopeAll: 'Všechny stránky',
      scopeScanned: 'Pouze naskenované ({count})',
      scopeRange: 'Rozsah stránek',
      rangeLabel: 'Stránky (např. 1-3, 5)',
      run: 'Spustit OCR',
      detecting: 'Hledám naskenované stránky…',
      progress: 'Rozpoznávám stránku {current} z {total}…',
      done: (count: number) =>
        plural(
          count,
          `OCR aplikováno na ${count} stránku`,
          `OCR aplikováno na ${count} stránky`,
          `OCR aplikováno na ${count} stránek`,
        ),
      noPages: 'Nebyly vybrány žádné stránky.',
      cancelling: 'Ruším…',
      allHaveText: 'Všechny stránky už obsahují vybíratelný text.',
    },
  },

  toasts: {
    opened: (name: string) => `Otevřeno: ${name}`,
    saved: (name: string) => `Uloženo: ${name}`,
    merged: (n: number) => `Sloučeno ${n} PDF`,
    createdFromImages: (n: number) =>
      plural(
        n,
        `Vytvořeno PDF z ${n} obrázku`,
        `Vytvořeno PDF z ${n} obrázků`,
        `Vytvořeno PDF z ${n} obrázků`,
      ),
    pagesInserted: (n: number) =>
      plural(n, `Vložena ${n} stránka`, `Vloženy ${n} stránky`, `Vloženo ${n} stránek`),
    splitIntoFiles: (n: number) =>
      plural(n, `Rozděleno na ${n} soubor`, `Rozděleno na ${n} soubory`, `Rozděleno na ${n} souborů`),
    pagesDeleted: (n: number) =>
      plural(n, `Smazána ${n} stránka`, `Smazány ${n} stránky`, `Smazáno ${n} stránek`),
    pagesExtracted: (n: number) =>
      plural(
        n,
        `Extrahována ${n} stránka`,
        `Extrahovány ${n} stránky`,
        `Extrahováno ${n} stránek`,
      ),
    nothingToUndo: 'Není co vrátit zpět',
    nothingToRedo: 'Není co zopakovat',
    copiedToClipboard: 'Zkopírováno',
    largeFileWarning: (mb: number) =>
      `Tento soubor má ${mb} MB. Úpravy velkých souborů mohou být pomalé — buďte prosím trpěliví.`,
  },

  errors: {
    genericOpen: 'Omlouváme se, tento soubor se nepodařilo otevřít.',
    notAPdf: 'Tohle nevypadá jako soubor PDF.',
    corrupt:
      'Toto PDF je zřejmě poškozené a nepodařilo se ho načíst. Vaše ostatní práce je v bezpečí.',
    encrypted: 'Toto PDF je chráněné heslem. Pro otevření zadejte jeho heslo.',
    wrongPassword: 'Toto heslo není správné. Zkuste to prosím znovu.',
    unsupportedEncryption:
      'Toto PDF používá metodu šifrování, kterou tento editor neumí otevřít.',
    imageLoad: 'Tento obrázek se nepodařilo načíst.',
    saveFailed: 'Ukládání selhalo. Váš načtený dokument zůstal beze změny.',
    tooLarge: 'Tento soubor je velmi velký a nemusí fungovat spolehlivě.',
    passwordPrompt: 'Heslo',
    unlock: 'Odemknout',
  },

  empty: {
    noPages: 'Žádné stránky k zobrazení.',
    noDocument: 'Otevřete PDF a začněte upravovat.',
  },
}
