/*
 * All user-facing English strings live here. Centralized so other languages can
 * be added later without touching component code. Import `t` everywhere.
 * Functions are used for strings that interpolate values.
 */

export const en = {
  appName: 'pedift',
  tagline: 'Private PDF editing, right in your browser',

  privacy: {
    badge: 'Private & offline',
    line: 'Your files never leave this device. Nothing is uploaded — all editing happens in your browser.',
  },

  theme: {
    toLight: 'Switch to light mode',
    toDark: 'Switch to dark mode',
  },

  landing: {
    dropTitle: 'Drop a PDF here, or click to open',
    dropHint: 'or pick a file from your computer',
    dropActive: 'Release to open',
    openButton: 'Open a PDF',
    quickToolsTitle: 'Quick tools',
    quickToolsHint: 'One-shot jobs — no need to open the editor',
    or: 'or',
    saveThisPage: 'Save this page for offline use',
  },

  quickTools: {
    merge: { title: 'Merge PDFs', desc: 'Combine several PDFs into one' },
    imagesToPdf: { title: 'Images → PDF', desc: 'Turn JPG/PNG images into a PDF' },
    compress: { title: 'Compress', desc: 'Shrink a PDF by re-encoding images' },
    protect: { title: 'Protect / Unprotect', desc: 'Add or remove a password' },
  },

  common: {
    cancel: 'Cancel',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    apply: 'Apply',
    save: 'Save',
    download: 'Download',
    add: 'Add',
    remove: 'Remove',
    delete: 'Delete',
    duplicate: 'Duplicate',
    rotate: 'Rotate',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    optional: 'optional',
    of: 'of',
    page: 'Page',
    pages: 'Pages',
    all: 'All',
    none: 'None',
    loading: 'Working…',
    dragToReorder: 'Drag to reorder',
    addFiles: 'Add files',
    addMore: 'Add more',
    chooseFiles: 'Choose files',
    moveUp: 'Move up',
    moveDown: 'Move down',
    dismiss: 'Dismiss',
    fromPage: 'From page',
    toPage: 'To page',
  },

  workspace: {
    documentMenu: 'Document',
    save: 'Save PDF',
    saving: 'Saving…',
    saved: 'Downloaded',
    undo: 'Undo',
    redo: 'Redo',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fitPage: 'Fit page',
    fitWidth: 'Fit width',
    closeDocument: 'Close document',
    closeConfirm: 'Close this document? Any unsaved edits will be discarded.',
    pagesPanel: 'Pages',
    pageOf: (n: number, total: number) => `Page ${n} of ${total}`,
    selectedCount: (n: number) => `${n} selected`,
  },

  tools: {
    select: 'Select',
    text: 'Text box',
    replaceText: 'Replace text',
    highlight: 'Highlight',
    pen: 'Pen',
    shapes: 'Shapes',
    rectangle: 'Rectangle',
    ellipse: 'Ellipse',
    line: 'Line',
    arrow: 'Arrow',
    whiteout: 'Whiteout',
    image: 'Insert image',
    signature: 'Signature',
    stamp: 'Stamp',
    pageNumbers: 'Page numbers',
    watermark: 'Watermark',
    color: 'Color',
    fill: 'Fill',
    strokeWidth: 'Stroke width',
    fontSize: 'Font size',
    font: 'Font',
    opacity: 'Opacity',
  },

  pagesPanel: {
    reorder: 'Reorder (drag)',
    rotateLeft: 'Rotate left',
    rotateRight: 'Rotate right',
    delete: 'Delete page(s)',
    duplicate: 'Duplicate page(s)',
    extract: 'Extract to new PDF',
    split: 'Split…',
    insert: 'Insert pages…',
    crop: 'Crop…',
    exportImage: 'Export as image…',
    deleteConfirm: (n: number) =>
      n === 1 ? 'Delete this page?' : `Delete these ${n} pages?`,
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
  },

  documentMenu: {
    fillForms: 'Fill forms',
    flatten: 'Flatten',
    metadata: 'Metadata…',
    protect: 'Protect / Unprotect…',
    compress: 'Compress…',
    properties: 'Properties',
  },

  dialogs: {
    merge: {
      title: 'Merge PDFs',
      hint: 'Add two or more PDFs, drag to set the order, then merge.',
      empty: 'Add at least two PDFs to merge.',
      mergeButton: 'Merge & download',
    },
    imagesToPdf: {
      title: 'Images → PDF',
      hint: 'Add JPG or PNG images, set the order, choose a page size.',
      pageSize: 'Page size',
      orientation: 'Orientation',
      a4: 'A4',
      letter: 'Letter',
      fitImage: 'Fit to image',
      portrait: 'Portrait',
      landscape: 'Landscape',
      margin: 'Margin',
      createButton: 'Create & download',
      empty: 'Add at least one image.',
    },
    compress: {
      title: 'Compress PDF',
      hint: 'Re-encodes embedded images at lower quality. Results vary by document — this is best-effort and never guarantees a ratio.',
      quality: 'Image quality',
      qualityLow: 'Smaller file',
      qualityHigh: 'Better quality',
      analyzing: 'Analyzing images…',
      before: 'Original',
      after: 'Compressed',
      saved: (pct: number) => `${pct}% smaller`,
      larger: 'Already optimized — no smaller version produced',
      compressButton: 'Compress & download',
    },
    protect: {
      title: 'Protect / Unprotect',
      mode: 'What do you want to do?',
      addPassword: 'Add a password',
      removePassword: 'Remove a password',
      newPassword: 'New password',
      confirmPassword: 'Confirm password',
      currentPassword: 'Current password',
      mismatch: 'Passwords do not match.',
      empty: 'Enter a password.',
      protectButton: 'Protect & download',
      unprotectButton: 'Unprotect & download',
      unsupportedTitle: 'Password protection unavailable',
      unsupported:
        'This build cannot add or remove PDF passwords reliably, so the feature is disabled to avoid producing broken files.',
    },
    split: {
      title: 'Split PDF',
      byRanges: 'By page ranges',
      everyN: 'Every N pages',
      rangesLabel: 'Ranges (e.g. 1-3, 4, 5-8)',
      everyNLabel: 'Pages per file',
      note: 'Each part downloads as a separate file.',
      splitButton: 'Split & download',
      invalidRanges: 'Enter valid page ranges within 1–{total}.',
    },
    insert: {
      title: 'Insert pages',
      pickFile: 'Choose a PDF to insert from',
      whichPages: 'Which pages',
      allPages: 'All pages',
      somePages: 'Pages (e.g. 1-3, 5)',
      position: 'Insert at',
      beforePage: (n: number) => `Before page ${n}`,
      atEnd: 'At the end',
      insertButton: 'Insert',
    },
    crop: {
      title: 'Crop',
      hint: 'Drag a rectangle on the page to set the visible area.',
      applyTo: 'Apply to',
      thisPage: 'This page',
      allPages: 'All pages',
      reset: 'Reset',
      applyButton: 'Apply crop',
    },
    exportImage: {
      title: 'Export as image',
      format: 'Format',
      png: 'PNG',
      jpg: 'JPG',
      scale: 'Scale',
      exportButton: 'Export & download',
    },
    metadata: {
      title: 'Document properties',
      titleField: 'Title',
      author: 'Author',
      subject: 'Subject',
      keywords: 'Keywords (comma-separated)',
      saveButton: 'Apply',
    },
    pageNumbers: {
      title: 'Page numbers',
      position: 'Position',
      topLeft: 'Top left',
      topCenter: 'Top center',
      topRight: 'Top right',
      bottomLeft: 'Bottom left',
      bottomCenter: 'Bottom center',
      bottomRight: 'Bottom right',
      format: 'Format',
      formatPlain: '1',
      formatSlash: '1 / N',
      formatLong: 'Page 1 of N',
      startAt: 'Start at',
      range: 'Pages',
      addButton: 'Add page numbers',
    },
    watermark: {
      title: 'Watermark',
      text: 'Watermark text',
      placeholder: 'e.g. CONFIDENTIAL',
      addButton: 'Add watermark',
      applyTo: 'Pages',
    },
    signature: {
      title: 'Signature',
      draw: 'Draw',
      type: 'Type',
      clear: 'Clear',
      typePlaceholder: 'Type your name',
      useButton: 'Place signature',
      reuse: 'Saved signatures',
    },
    fillForms: {
      title: 'Fill form fields',
      none: 'No fillable form fields were found in this document.',
      saveButton: 'Apply & continue',
    },
    flatten: {
      title: 'Flatten document',
      hint: 'Bakes form fields and annotations into the page so they can no longer be edited. This cannot be undone after saving.',
      flattenButton: 'Flatten',
    },
    stamp: {
      title: 'Stamp',
      approved: 'APPROVED',
      draft: 'DRAFT',
      confidential: 'CONFIDENTIAL',
      check: 'Check',
      cross: 'Cross',
      date: "Today's date",
    },
    replaceText: {
      note: 'Replace text covers the old text and lets you retype it. The font may look different from the original.',
      gotIt: "Got it",
    },
  },

  toasts: {
    opened: (name: string) => `Opened ${name}`,
    saved: (name: string) => `Saved ${name}`,
    merged: (n: number) => `Merged ${n} PDFs`,
    pagesDeleted: (n: number) => `Deleted ${n} page${n === 1 ? '' : 's'}`,
    pagesExtracted: (n: number) => `Extracted ${n} page${n === 1 ? '' : 's'}`,
    nothingToUndo: 'Nothing to undo',
    nothingToRedo: 'Nothing to redo',
    copiedToClipboard: 'Copied',
    largeFileWarning: (mb: number) =>
      `This file is ${mb} MB. Editing large files may be slow — please be patient.`,
  },

  errors: {
    genericOpen: 'Sorry, this file could not be opened.',
    notAPdf: 'That does not look like a PDF file.',
    corrupt:
      'This PDF appears to be damaged and could not be read. Your other work is safe.',
    encrypted: 'This PDF is password-protected. Enter its password to open it.',
    wrongPassword: 'That password is not correct. Please try again.',
    unsupportedEncryption:
      'This PDF uses an encryption method this editor cannot open.',
    imageLoad: 'That image could not be loaded.',
    saveFailed: 'Saving failed. Your loaded document is unchanged.',
    tooLarge: 'This file is very large and may not work reliably.',
    passwordPrompt: 'Password',
    unlock: 'Unlock',
  },

  empty: {
    noPages: 'No pages to show.',
    noDocument: 'Open a PDF to start editing.',
  },
} as const

export type Strings = typeof en

/** The active string table. Swap here when adding languages. */
export const t: Strings = en
