// Reads raw OCR binary assets from src/ocr/vendor/raw/, gzip-compresses them,
// base64-encodes, and emits TS modules under src/ocr/vendor/ for inlining into
// the single-file build. Run before `npm run build` for the OCR edition.
import { readFileSync, writeFileSync } from 'node:fs'
import { gzipSync } from 'node:zlib'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const rawDir = join(root, 'src', 'ocr', 'vendor', 'raw')
const outDir = join(root, 'src', 'ocr', 'vendor')

const files = [
  { raw: 'tesseract-core.wasm', out: 'wasm.gen.ts',  export: 'WASM_GZ_B64' },
  { raw: 'eng.traineddata',     out: 'eng.gen.ts',   export: 'ENG_GZ_B64'  },
  { raw: 'ces.traineddata',     out: 'ces.gen.ts',   export: 'CES_GZ_B64'  },
  { raw: 'DejaVuSans.ttf',      out: 'font.gen.ts',  export: 'FONT_GZ_B64' },
]

for (const { raw, out, export: exportName } of files) {
  const rawPath = join(rawDir, raw)
  let buf
  try {
    buf = readFileSync(rawPath)
  } catch {
    console.error(`ERROR: missing raw file: ${rawPath}`)
    process.exit(1)
  }

  const gz = gzipSync(buf, { level: 9 })
  const b64 = gz.toString('base64')

  const outPath = join(outDir, out)
  writeFileSync(outPath, `// AUTO-GENERATED by scripts/prebuild-ocr.mjs — do not edit\nexport const ${exportName} = ${JSON.stringify(b64)}\n`)

  console.log(`${raw}: ${(buf.length / 1024).toFixed(0)} KB → ${(gz.length / 1024).toFixed(0)} KB gz (${out})`)
}
